# Sensitive information is stored in config/application.properties
# https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: from config/application.properties locally or env var elsewhere