# Sensitive information is stored in config/application.properties
# https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files
spring:
  port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orderservice_user  # From postgres-initscripts/01_add_orderservice_user_and_database.sh
    password: from config/application.properties locally or env var elsewhere
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


kafka:
  bootstrap-servers: localhost:19092
  orders-topic-name: orderservice.internal.public.orders
  order-items-topic-name: orderservice.internal.public.items
  public-orders-topic-name: orderservice.public.orders
  offset: earliest-offset # latest-offset
